version: 1 

disable_existing_loggers: false

formatters:
  verbose:
    format: '%(levelname)s %(asctime)s %(module)s %(message)s'

handlers:
  console:
    level: DEBUG 
    class: logging.StreamHandler
    formatter: verbose
  file:
    level: DEBUG  
    class: logging.handlers.TimedRotatingFileHandler
    formatter: verbose
    filename: /app/logs/ocrworker.log
    when: midnight
    interval: 1
    backupCount: 60

loggers:
  root:
    level: DEBUG 
    handlers: [console, file]